version: '3'

services:
    app-mysql:
        image: mysql:5.6.42
        container_name: typescript-mysql
        volumes:
            - "./.docker/volumes/mysql:/var/lib/mysql"
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=123456

networks:
    postgres:
        driver: bridge